version: 0.2
phases:
  pre_build:
    commands:
      - echo Restore started on 'date'
      - dotnet restore Books.Api/Books.Api.csproj
  build:
    commands:
      - echo build started on 'date'
      - dotnet publish -c release -o app Books.Api/Books.Api.csproj
  
artifacts:
  files:
    - app/**/*
    - scripts/**/*
    - appspec.yml